mysite/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('characters.urls')),
    path('', include('traits.urls'))#,
    #path('', include('pub.urls'))
]

pub/urls.py
from django.conf.urls import url
from pubs.views import PubCreateView, export_pubs_csv

urlpatterns = [
    url(r'^pub/create/$', PubCreateView.as_view(success_url = 'successful_upload.html'), name="create pub"),
    url(r'^export/pubs/csv/$', export_pubs_csv, name='export_pubs_csv'),

]

pub_sai/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from pub import views

urlpatterns = [
    url(r'^browse/$',views.browse_pubs, name="pub_browse_base"),
    url(r'^browse/query$',views.browse_query_pubs, name="pub_browse_query"),
    url(r'^browse/([a-zA-Z0-9_-]+)/$',views.browse_single, name="pub_browse_single"),
    url(r'^browse/([a-zA-Z0-9_-]+)/update$',views.pub_update, name="pub_update"),
    url(r'^browse/([a-zA-Z0-9_-]+)/delete$',views.pub_delete, name="pub_delete"),
    url(r'^bfile/$', views.upload_bfile, name="pub_browse_upload_bfile"),
    url(r'^single/$',views.enter_single_publication, name="pub_browse_upload_single")
]

traits/models.py
import csv
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator

from django.contrib.contenttypes.fields import GenericRelation

from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from crispy_forms.bootstrap import InlineCheckboxes
from pub.models import Pub

# variables for validation: check for alphanumeric chars, alpha chars, and numeric chars, respectively
val_alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Error: only alphanumeric characters are allowed.')
val_alpha = RegexValidator(r'^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')
val_numeric = RegexValidator(r'^[0-9]*$', 'Error: only numeric characters are allowed.')

class Trait(models.Model):
    # might implement the following 'Meta' class addition at some point (Sai had this)
    #class Meta:
    #    permissions = (
    #        ('view_trait', 'Can view trait'),
    #    )
    genus = models.CharField(max_length=50, null=True, blank=False, validators=[val_alpha])#help_text= 'Enter data if known. Expects str as input')
    species = models.CharField(max_length=50, null=True, blank=False, validators=[val_alpha])
    isi = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0.0, message='Must be a number between 0.0 and 1.0'), MaxValueValidator(1.0, message='Must be a number between 0.0 and 1.0')])
    
    FRUIT_TYPE_CHOICES = (('capsule','capsule'), ('CAPSULE', 'CAPSULE'), ('Capsule', 'Capsule'),('berry','berry'), ('Berry', 'Berry'), ('BERRY', 'BERRY')) # check why need doubles 
    fruit_type = models.CharField(max_length=50, null=False, default='none', choices=FRUIT_TYPE_CHOICES)
    pub = models.ForeignKey(Pub, on_delete=models.CASCADE, null=True, db_column='citekey', related_name='+', default='2')#default='Koch2012', validators=[val_alphanumeric])
# step 1: fix migrations to allow foreign key publication line (29 here) to work
# add trait --> citekey field should have something there: see what it looks like (does it list all pubs that 
# have been imported already? get a better sense of what's here)

# csv practice code below

#with open("/Users/JMK/traits-example_short.csv", mode = "r") as infile, open("traits-example_cleaned.csv", "r") as outfile:      reader = csv.reader(infile) #reading input csv file
#        next(reader, None) #skips headers
#        writer = csv.writer(outfile) #allows specified outfile to be written to
#        for row in reader: #iterating through rows in csv
#            Trait.objects.get_or_create(
#                isi=row[7],
#                fruit_type=row[21],
#                genus=row[1],
#                species=row[2],
#                )
            # get_or_create creates a tuple of the new object or
            # current object and a boolean of if it was created

pub_sai/forms.py
from django import forms
from django.forms import ModelForm
from pub.models import  Pub, Person
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit

class BibtexForm(forms.Form):
    file_name = forms.FileField()


class PubForm(ModelForm):
    class Meta:
        model = Pub
        fields = ['type','address','annotate','lastName','middleName','firstName','booktitle','chapter','crossref',
            'edition','editor','howpublished','institution','journal',
            'citekey','month','note','number','organization','pages',
            'publisher','school','series','title','volume','year']

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        #article, book, incollection, manual, misc, phdthesis, unpublished are some common types

        self.helper.layout = Layout(
            Fieldset(
                'Entry Type',
                'type',
                'citekey',
            ),
            Fieldset(
                'People',
                'lastName',
                'middleName',
                'firstName',
                'editor'
            ),

            Fieldset(
                'Fields',
                 'address', 'annotate', 'booktitle', 'chapter', 'crossref',
                 'edition', 'howpublished', 'institution', 'journal',
                 'month', 'note', 'number', 'organization', 'pages',
                 'publisher', 'school', 'series', 'title', 'volume', 'year'
            ),
            ButtonHolder(
                Submit('create', 'Create Pub', css_class='button white')
            )

        )
        super(PubForm, self).__init__(*args, **kwargs)


class PubUpdateForm(ModelForm):
    comment = forms.CharField(label="Update comment:",required=True)    #user needs to make a comment when updating fields
    class Meta:
        model = Pub
        fields = ['type','address','annotate','lastName','middleName','firstName','booktitle','chapter','crossref',
            'edition','editor','howpublished','institution','journal',
            'citekey','month','note','number','organization','pages',
            'publisher','school','series','title','volume','year']

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        #article, book, incollection, manual, misc, phdthesis, unpublished are some common types

        self.helper.layout = Layout(
            Fieldset(
                'Update Comment',
                'comment',
            ),
            Fieldset(
                'Entry Type',
                'type',
                'citekey',
            ),
            Fieldset(
                'People',
                'lastName',
                'middleName',
                'firstName',
                'editor'
            ),

            Fieldset(
                'Fields',
                 'address', 'annotate', 'booktitle', 'chapter', 'crossref',
                 'edition', 'howpublished', 'institution', 'journal',
                 'month', 'note', 'number', 'organization', 'pages',
                 'publisher', 'school', 'series', 'title', 'volume', 'year'
            ),
            ButtonHolder(
                Submit('update', 'Update Pub', css_class='button white')
            )

        )
        super(PubUpdateForm, self).__init__(*args, **kwargs)


class PubSearchForm(ModelForm):
    class Meta:
        model = Pub
        fields = ['type','address','annotate','lastName','middleName','firstName','booktitle','chapter','crossref',
            'edition','editor','howpublished','institution','journal',
            'citekey','month','note','number','organization','pages',
            'publisher','school','series','title','volume','year']

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        abstract = forms.CharField(required=False)
        address = forms.CharField(max_length=50, required=False)
        annotate = forms.CharField(max_length=50, required=False)
        #author = forms.ModelChoiceField(Person, required=False)
        lastName = forms.CharField(max_length=50, required=False)
        middleName = forms.CharField(max_length=50, required=False)
        firstName = forms.CharField(max_length=50, required=False)
        booktitle = forms.CharField(max_length=50, required=False)
        chapter = forms.CharField(max_length=50, required=False)
        crossref = forms.CharField(max_length=50, required=False)
        doi = forms.CharField(max_length=50, required=False)
        edition = forms.CharField(max_length=50, required=False)
        editor = forms.ModelChoiceField(Person, required=False)
        howpublished = forms.CharField(max_length=50, required=False)
        institution = forms.CharField(max_length=50, required=False)
        journal = forms.CharField(max_length=50, required=False)
        citekey = forms.CharField(max_length=50, required=False)
        keywords = forms.CharField(max_length=50, required=False)
        month = forms.CharField(max_length=50, required=False)
        note = forms.CharField(max_length=50,required=False)
        number = forms.CharField(max_length=50, required=False)
        organization = forms.CharField(max_length=50, required=False)
        pages = forms.CharField(max_length=50, required=False)
        publisher = forms.CharField(max_length=50, required=False)
        school = forms.CharField(max_length=50, required=False)
        series = forms.CharField(max_length=50, required=False)
        title = forms.CharField(max_length=50, required=False)
        TYPE_CHOICES = (('article', 'article'), ('book', 'book'), ('incollection','incollection'),
                        ('manual', 'manual'), ('misc', 'misc'),
                        ('unpublished', 'unpublished'))
        #type = forms.ModelChoiceField(max_length=50, required=False,choices=TYPE_CHOICES)
        type = forms.CharField(max_length=50, required=False)
        volume = forms.CharField(max_length=50, required=False)
        year = forms.CharField(max_length=50, required=False)
        url = forms.CharField(max_length=50, required=False)
        super(PubSearchForm, self).__init__(*args, **kwargs)

pub_sai/views.py
from django.shortcuts import render
from scripts import upload_pubs
from django.template.context_processors import csrf
import sys,os
import time
from pub.models import Pub
from django.contrib.auth.models import User
from pub.PubDataManager import PubDataManager
from pub.forms import *
from django.forms.models import model_to_dict
from django.core.files.storage import FileSystemStorage
from pub.pub_field_types import get_field_types


# Create your views here.

pub_data_manager = PubDataManager()

#views for browsing Publications
def browse_pubs(request):
    """
    Returns all the Pub records (publications)
    :param request: incoming HTTP request
    :return: HTTP response with all the Pub records
    """
    args = {}
    pubs,_ = pub_data_manager.browse_query_pubs(request.user,{},None)
    search_form = PubSearchForm()
    args['pubs']=pubs
    args['search_form']=search_form
    return render(request, 'browse_pubs.html',args)

def browse_query_pubs(request):
    info_list = []; success_list=[]; warning_list=[];danger_list=[]
    args = {'info_alerts':info_list, 'success_alerts':success_list,'warning_alerts':warning_list,'danger_alerts':danger_list}
    query_params = {}
    fields = [f.name for f in Pub._meta.get_fields()]
    for field in request.POST.citekeys():
        try:
            if field in request.POST and field in fields :
                if request.POST[field]!='' and request.POST[field]!=None:
                    query_params[field]=request.POST[field]
        except:
            continue
    query_data, query_params = pub_data_manager.browse_query_pubs(request.user,query_params,request.POST['match_type'])
    search_form = PubSearchForm()
    args['search_form']=search_form
    args['pubs'] = query_data
    args['query_params'] = query_params
    return render(request,'browse_pubs.html',args)

def browse_single(request,citekey):
    """
    Returns specific information regarding a single publication given citation key
    :param request: incoming HTTP response
    :param key: ciation key (unique to each Pub)
    :return: HTTP respose with the Pub record
    """
    args = {}
    pub = pub_data_manager.browse_single_pub(request.user,citekey)
    args['pub']=pub
    return render(request, 'pub_detail2.html',args)


#views for editing/deleting
def pub_update(request,citekey):
    """
    Updates a Pub
    :param request: incoming HTTP request
    :param key: citation key of the Pub record to be updated
    :return: HTTP response with the updated pub or HTTP response indicating failure
    """
    info_alerts =[]; success_alerts=[]; warning_alerts = []; danger_alerts=[];
    args = {'info_alerts': info_alerts, 'success_alerts': success_alerts, 'warning_alerts': warning_alerts,'danger_alerts': danger_alerts}
    pub = pub_data_manager.browse_single_pub(request.user, citekey)
    if request.POST:
        success = pub_data_manager.update_pub(request.user,citekey,request.POST)
        if success:
            success_alerts.append(citekey + " successfully updated.")
        else:
            danger_alerts.append(citekey + " was not successfully updated.")
        args['pub'] = pub
        return render(request,'pub_detail2.html',args)
    else:
        form = PubUpdateForm(initial=model_to_dict(pub))
        args['form'] = form
        args['pub'] = pub
        return render(request, 'pub_update2.html',args)

def pub_delete(request,citekey):
    """
    Deletes a Pub record with citation key key
    :param request: incoming HTTP response
    :param key: citation key of Pub to be deleted
    :return: HTTP response indicating success or failure
    """
    info_alerts =[]; success_alerts=[]; warning_alerts = []; danger_alerts=[];
    args = {'info_alerts':info_alerts, 'success_alerts':success_alerts,'warning_alerts':warning_alerts,'danger_alerts':danger_alerts}
    args['pub'] = pub_data_manager.browse_single_pub(request.user,citekey)
    if request.POST:
        success = pub_data_manager.delete_pub(request.user,citekey)
        if success:
            success_alerts.append(citekey + " successfully deleted. It no longer exists in the system.")
        else:
            danger_alerts.append(citekey + " was not deleted. It still exists in the system.")
    args.update(csrf(request))
    return render(request, 'delete_pub.html',args)


#Views for adding Publications
def upload_bfile(request):
    """
    Uploads and inserts Pub records specified by publication entries in a bibtex file
    :param request: incoming HTTP request
    :return: HTTP response indicating success or failure
    """
    """Uploads and inserts the publications in a given bibtex into the database"""
    info_alerts =[]; success_alerts=[]; warning_alerts = []; danger_alerts=[];
    args = {'info_alerts':info_alerts, 'success_alerts':success_alerts,'warning_alerts':warning_alerts,'danger_alerts':danger_alerts}
    form = BibtexForm()
    #Handle POST
    if request.POST:
        form = BibtexForm(request.POST, request.FILES)
        if form.is_valid():
            bibfile = request.FILES['file_name']
            fs = FileSystemStorage()
            bib_filename = fs.save(bibfile.name,bibfile)
            (success,errors) = pub_data_manager.upload_pubs_bibtex(request.user,fs.path(bib_filename) )
            args['success']=success
            args['success_count']=len(success)
            args['errors']=errors
            args['errors_count']=len(errors)
            success_alerts.append(str(len(success))+" publications uploaded successfully.")
            danger_alerts.append(str(len(errors))+" publications upload failed.")
        else:
            danger_alerts.append("File path not found.")
            
    args['form']=form
    args.update(csrf(request))
    return render(request, 'upload_bibtex.html',args)

def enter_single_publication(request):
    """
    Inserts a single publication into the database
    :param request: incoming HTTP request
    :return: HTTP response with info regarding success or failure
    """
    """Inserts a single publication into the database"""
    info_alerts =[]; success_alerts=[]; warning_alerts = []; danger_alerts=[];
    args = {'info_alerts':info_alerts, 'success_alerts':success_alerts,'warning_alerts':warning_alerts,'danger_alerts':danger_alerts}

    if request.POST:
        success = []
        errors = []
        (success,errors) = pub_data_manager.enter_single_pub(request.user,request.POST)
        args['success']=success
        args['success_count']=len(success)
        args['errors']=errors
        args['errors_count']=len(errors)
        if len(success)>0:
            success_alerts.append("Publication entry was successful.")
        else:
            danger_alerts.append("Publication entry failed. Please check required fields.")

    form = PubForm()
    args['form']=form
    args['fields']= get_field_types()
    return render(request,'upload_single_pub2.html',args)

pub_sai/templates/browse_pubs.html
{% extends "base.html" %}
{% block sidebar %}

    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"></script>


    <style>
    .scrollable-menu {
    height: auto;
    max-height: 500px;
    overflow-x: hidden;
    }

    .tbody{
        border-top-width: 10px;
    }

    .ul_three_columns {
      columns: 3;
      -webkit-columns: 3;
      -moz-columns: 3;
    }


    table, td {
        overflow:hidden;
    }

    th:: after{
        content: "--r"
    }
    </style>
    <!--Search and Filter -->

    <ul class="nav nav-tabs nav-stacked">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Query Database <b class="caret"></b></a>
            <ul class="ul_three_columns dropdown-menu scrollable-menu list-group">
                <form class="sidebar-form" action={% url 'pub_browse_query' %} method="post" role="query" required="false">{% csrf_token %}

                    <li>
                        <button type="submit">Search!</button>
                        <button type="reset">Reset!</button>
                        </br>
                        <input type="radio" name="match_type" value="partial">Partial<br>
                        <input type="radio" name="match_type" value="exact" checked="checked">Exact<br>

                    </li>

                    {% if search_form %}
                        {% load crispy_forms_tags %}
                        {% crispy search_form %}
                    {% endif %}
                </form>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Filter Results <b class="caret"></b></a>
        </li>
    </ul>


    <!-- Download Bibtex-->

    <form role="form" action ="/pubs/browse/download" method="post">{% csrf_token %}
        <div class="form-group">
        <input class="form-control" id="download_bibtex" style="visibility:hidden" name="download_bibtex" type="text" value="download"/>
        <button type="submit" class="btn btn-default" aria-label="Left Align" id="download">
                <span class="" aria-hidden="true" value="download">Download Bibtex</span>
        </button>
        </div>
    </form>

    <!-- Query and Filter Information-->
    {% if query_params %}
        <div class="alert alert-info">
        <p>Current Query Results</br>Field: query_string</p>
        <ul>
        {% for citekey,value in query_params.items %}
            <li>{{ citekey}}:{{value }}</li>
        {% endfor %}
        </ul>
        </div>
    {% endif %}



    <!--Alerts -->
        {% for success in success_alerts %}
        <div class="alert alert-success" role="alert">
            <strong>{{success}}</strong>
        </div>
        {% endfor %}
        {% for info in info_alerts %}
        <div class="alert alert-info" role="alert">
            <strong>{{info}}</strong>
        </div>
        {% endfor %}
        {% for warning in warning_alerts %}
        <div class="alert alert-warning" role="alert">
            <strong>{{warning}}</strong>
        </div>
        {% endfor %}
        {% for danger in danger_alerts %}
        <div class="alert alert-danger" role="alert">
            <strong>{{danger}}</strong>
        </div>
        {% endfor %}
{% endblock %}
{% block content %}
    <style>
    .data-wrapper { height: 1000px; width: 1000px;}
    .data-wrapper { height: 100px;}
</style>

    <h1>Publications</h1>
    {% if user.is_authenticated %}
    <div id="datawrapper" class="data-wrapper">
        <p>Note: To sort columns, click on column heading.</p>
    <table id="pub_data_table" class="table table-hover data-wrapper">
        <thead>
            <th>Publication Title</th>
            <th>Authors</th>
            <th>Year</th>
        </thead>
        <tbody>
        {%for pub in pubs%}
            <tr>
                <td><a href={{pub.key}}>{{pub.title}}</a></td>
                <td>{% for author in pub.author.all %} {{ author }}{% if not forloop.last %},{% endif %}{% endfor %}</td>
                <td>{{pub.year}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <script>
    $(document).ready(function(){
        $('#pub_data_table').DataTable({
        searching: false,
        paging: false
        });
    });
    </script>
    </div>

    {% else %}
    <p>You must be logged in to see this page</p>
    {% endif %}
{% endblock %}

pub_sai/templates/delete_pub.html
{% extends "base.html" %}
{% block sidebar %}
            
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'pub_browse_base' %}">Back to Publications</a></li>
                <li><a href="{% url 'pub_browse_single' pub.citekey %}">Back to Publication detail</a></li>

            </ul>
            <br>{% csrf_token %}
            {% for success in success_alerts %}
            <div class="alert alert-success" role="alert">
                <strong>{{success}}</strong>
            </div>
            {% endfor %}
            {% for info in info_alerts %}
            <div class="alert alert-info" role="alert">
                <strong>{{info}}</strong> 
            </div>
            {% endfor %}
            {% for warning in warning_alerts %}
            <div class="alert alert-warning" role="alert">
                <strong>{{warning}}</strong>
            </div>
            {% endfor %}
            {% for danger in danger_alerts %}
            <div class="alert alert-danger" role="alert">
                <strong>{{danger}}</strong>
            </div>
            {% endfor %}
{% endblock %}
{% block content %}
    <style>
        .editable_field {
            visibility: hidden
        }
    </style>

    <h1>Delete Publication: {{pub.citekey}}</h1>
    {% if user.is_authenticated %}
    <p>Are you sure you want to delete this publication? It will be recorded as deleted under your user account. You will note be able to undo this action.</p>
    
    <table>
        <tr>
            <td>
                <div>
                    <form method="post" action="{% url 'pub_delete' pub.citekey %}">{% csrf_token %}
                        <button type="submit" class="btn btn-primary">Delete</button>
                    </form>
                </div>
            </td>
            <td>    
                <div class="col-lg-2">
                    <form method="get" action="{% url 'pub_browse_single' pub.citekey %}">{% csrf_token %}
                        <button type="submit" class="btn btn-danger">Cancel</button>
                    </form>
                </div>
            </td>
        </tr>
    </table>

    
    {% else %}
    <p>You must be logged in to see this page</p>
    {% endif %}
    

{% endblock %}

pub_sai/templates/pub_detail2.html
{% extends "base.html" %}
{% block sidebar %}

            <ul class="nav nav-sidebar">
                <li><a href="{% url 'pub_browse_base' %}">Back to Publication</a>
                <li><a href="{% url 'pub_update' pub.citekey %}">Update Publication</a>
                <li><a href="{% url 'pub_delete' pub.citekey %}">Delete Publication</a>

            </ul>
            <br>{% csrf_token %}
            {% for success in success_alerts %}
            <div class="alert alert-success" role="alert">
                <strong>{{success}}</strong>
            </div>
            {% endfor %}
            {% for info in info_alerts %}
            <div class="alert alert-info" role="alert">
                <strong>{{info}}</strong>
            </div>
            {% endfor %}
            {% for warning in warning_alerts %}
            <div class="alert alert-warning" role="alert">
                <strong>{{warning}}</strong>
            </div>
            {% endfor %}
            {% for danger in danger_alerts %}
            <div class="alert alert-danger" role="alert">
                <strong>{{danger}}</strong>
            </div>
            {% endfor %}
{% endblock %}
{% block content %}
    <style>
        .editable_field {
            visibility: hidden
        }
    </style>

    <h1>Publication Detail: {{pub.citekey}}</h1>
    {% if user.is_authenticated %}
    <table class="table table-hover data-wrapper">
        <thead>
            <th>
                Attribute
            </th>
            <th>
                Current Value
            </th>
            <th class="editable_field">
                Update
            </th>
        </thead>

        <tbody>

                <tr class="pub_detail_row"><td><strong>Address</strong></td><td>{{pub.address}}</td><td><input class="editable_field" value={{pub.address}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Annote</strong></td><td>{{pub.annote}}</td><td><input class="editable_field" value={{pub.annote}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Author</strong></td><td>{% for author in pub.author.all %} {{ author }}, {% endfor %}</td><td><input class="editable_field" value={{pub.author}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Booktitle</strong></td><td>{{pub.booktitle}}</td><td><input class="editable_field" value={{pub.booktitle}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Chapter</strong></td><td>{{pub.chapter}}</td><td><input class="editable_field" value={{pub.chapter}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Crossref</strong></td><td>{{pub.crossref}}</td><td><input class="editable_field" value={{pub.crossref}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Edition</strong></td><td>{{pub.edition}}</td><td><input class="editable_field" value={{pub.edition}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Editor</strong></td><td>{% for editor in pub.editor.all %} {{ editor }}, {% endfor %}</td><td><input class="editable_field" value={{pub.editor}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Howpublished</strong></td><td>{{pub.howpublished}}</td><td><input class="editable_field" value={{pub.howpublished}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Institution</strong></td><td>{{pub.institution}}</td><td><input class="editable_field" value={{pub.institution}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Journal</strong></td><td>{{pub.journal}}</td><td><input class="editable_field" value={{pub.journal}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>CiteKey</strong></td><td>{{pub.citekey}}</td><td><input class="editable_field" value={{pub.citekey}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Month</strong></td><td>{{pub.month}}</td><td><input class="editable_field" value={{pub.month}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Note</strong></td><td>{{pub.note}}</td><td><input class="editable_field" value={{pub.note}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Number</strong></td><td>{{pub.number}}</td><td><input class="editable_field" value={{pub.number}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Organization</strong></td><td>{{pub.organization}}</td><td><input class="editable_field" value={{pub.organization}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Pages</strong></td><td>{{pub.pages}}</td><td><input class="editable_field" value={{pub.pages}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Publisher</strong></td><td>{{pub.publisher}}</td><td><input class="editable_field" value={{pub.publisher}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>School</strong></td><td>{{pub.school}}</td><td><input class="editable_field" value={{pub.school}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Series</strong></td><td>{{pub.series}}</td><td><input class="editable_field" value={{pub.series}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Title</strong></td><td>{{pub.title}}</td><td><input class="editable_field" value={{pub.title}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Type</strong></td><td>{{pub.type}}</td><td><input class="editable_field" value={{pub.type}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Volume</strong></td><td>{{pub.volume}}</td><td><input class="editable_field" value={{pub.volume}}></input></td></tr>
                <tr class="pub_detail_row"><td><strong>Year</strong></td><td>{{pub.year}}</td><td><input class="editable_field" value={{pub.year}}></input></td></tr>

        </tbody>
    </table>
    <table class="table table-hover data-wrapper">
        <tbody>
            <h3>Linked Traits</h3>
            {% for item in pub.trait_set.get_queryset %}
                <tr class="pub_detail_row"><td><a href="{% url 'traits_browse_single_species'  item.id%}">{{item}}</a></td></tr>
            {% endfor %}

        </tbody>
    </table>

    {% else %}
    <p>You must be logged in to see this page</p>
    {% endif %}


{% endblock %}